### ISSUE TITLE
Assertion failure from automated testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/gene-expression-essentials#4] opened 2015-06-10 20:19 UTC
```
Uncaught TypeError: manualGeneExpressionModel.reset is not a function
TypeError: manualGeneExpressionModel.reset is not a function
    at ManualGeneExpressionScreenView.ResetAllButton.listener (http://192.168.0.2:8080/gene-expression-basics/js/manualgeneexpression/view/ManualGeneExpressionScreenView.js?bust=1433967335625:40:35)
    at http://192.168.0.2:8080/sun/js/buttons/PushButtonModel.js?bust=1433967335625:78:9
    at Array.forEach (native)
    at PushButtonModel.inherit.fire (http://192.168.0.2:8080/sun/js/buttons/PushButtonModel.js?bust=1433967335625:77:12)
    at http://192.168.0.2:8080/sun/js/buttons/PushButtonModel.js?bust=1433967335625:45:25
    at Array.onValueObserver (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967335625:276:13)
    at Property.inherit._notifyObservers (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967335625:112:29)
    at Property.inherit._setAndNotifyObservers (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967335625:99:14)
    at Property.inherit.set (http://192.168.0.2:8080/axon/js/Property.js?bust=1433967335625:72:16)
    at PushButtonModel.Object.defineProperty.set [as down] (http://192.168.0.2:8080/axon/js/PropertySet.js?bust=1433967335625:136:43)
```

**Comment by aadish** [comment] 2016-09-20 22:32
cannot reproduce closing

**Closed by aadish** 2016-09-20 22:32 UTC
Labels: type:bug
