### ISSUE TITLE
mRNA text jittering as ribosome makes mRNA

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gene-expression-essentials#96] opened 2017-10-30 17:17 UTC
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra Version 10.12.6 (16G29)

**Browser:**

Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Problem description:**

Somewhat difficult to reproduce, but the mRNA text will jitter as the ribosome makes mRNA. This only works if you attach the ribosome to the  fairly quickly. I think this happens because the protein and the mRNA text overlap. This is for phetsims/QA#58.

**Steps to reproduce:**

1. Go to the third gene in the expression screen.
2. Attach positive transcription factors.
3. Attach polymerase.
4. Attach ribosome fairly quickly, but not too quickly. (You don't want #94 to occur.)

**Screenshots:**

![oct-30-2017 11-10-09](https://user-images.githubusercontent.com/31285590/32184993-97ebccdc-bd63-11e7-9355-d215495db152.gif)

**Troubleshooting information (do not edit):**

Name: ‪Gene Expression Essentials‬
URL: https://www.colorado.edu/physics/phet/dev/html/gene-expression-essentials/1.0.0-dev.13/gene-expression-essentials_en.html
Version: 1.0.0-dev.13 2017-10-25 21:56:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
Language: en-US
Window: 1438x700
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"80b60293","branch":"master"},"babel":{"sha":"ce29f350","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"6b338220","branch":"master"},"dot":{"sha":"85ef2bbf","branch":"master"},"gene-expression-essentials":{"sha":"a8b7efc7","branch":"master"},"joist":{"sha":"eb3a1951","branch":"master"},"kite":{"sha":"2c921cba","branch":"master"},"phet-core":{"sha":"c30d15ed","branch":"master"},"phetcommon":{"sha":"b13138d2","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"92a2872d","branch":"master"},"scenery-phet":{"sha":"d394b9df","branch":"master"},"sherpa":{"sha":"0d590744","branch":"master"},"sun":{"sha":"99a0abef","branch":"master"},"tandem":{"sha":"c1e98f69","branch":"master"}}

**Comment by jbphet** [comment] 2017-11-08 22:55
This problem is caused by the ribosome consuming the mRNA more rapidly that it is being produced, so its bounds end up changing radically while it is being synthesized.  The bounds are used to position the caption, hence the jumpiness.  This was addressed by https://github.com/phetsims/gene-expression-essentials/commit/ba4c80578664d112cad8863723e00fffcccfcb23, which as done for issue #94.  I've tested after the update, and the motion isn't perfectly smooth, but it is much improved and is as good as it was in the Java version.

**Comment by jbphet** [comment] 2017-11-08 22:56
Should be fixed, will unassign and have it verified on the next dev or RC release.

**Comment by brroberts1231** [comment] 2017-11-16 21:20
For phetsims/QA#68
Seems improved for genes 2 and 3, but gene 1 now looks noticeably worse than the other two.

**Comment by lmulhall-phet** [comment] 2017-11-27 16:38
Tested on several devices/browsers. Seems to be fixed.

**Closed** 2017-11-27 16:47 UTC
Labels: type:bug
