### ISSUE TITLE
fix title

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-essentials#8] opened 2015-09-10 22:23 UTC
The title is currently "Gene Expression - The Basics".  If this sim is following PhET conventions, the title should be "Gene Expression: Basics".

**Comment by jbphet** [comment] 2015-09-11 15:25
I believe that this sim was named before we had the whole "basics" thing going on for simpler versions of simulations.  The name "Gene Expression - The Basics" was intended to convey the idea that this sim teaches the basics of a very complex process, and not that it is a simpler version of another sim.  There is no plan to ever make a more complete, non-basic, version of this simulation.

Perhaps the sim should be renamed to avoid confusion with the basics/full terminology that PhET now uses.  Maybe "Gene Expression Essentials" or "Basic Gene Expression".  I'll assign to @ariel-phet to see if he things that this is worth doing.

**Comment by ariel-phet** [comment] 2015-09-11 15:27
Or perhaps "Gene Expression Fundamentals" or such? Let me get some designer opinions.

**Comment by ariel-phet** [comment] 2015-09-11 15:28
@amanda-phet see above...thoughts on changing the name if you put your teacher hat on?

**Comment by amanda-phet** [comment] 2015-09-14 21:03
Maybe @amyh-phet could also weigh in? I like "Gene Expression Essentials" out of the options presented above. I agree that using the new "SimName : Basics" convention does not fit in this case.

**Comment by amyh-phet** [comment] 2015-09-14 21:41
I think Gene Expression Essentials conveys that the sim introduces the topic but doesn't provide all of the information as the topic is really complex.     I like "Essentials" more than "Fundamentals".   I also think this would avoid the confusion with our current "SimName-Basics".

**Comment by aadish** [comment] 2016-08-24 18:49
@amanda-phet should I go ahead with Gene Expression Essentials name for this sim

**Comment by amanda-phet** [comment] 2016-08-24 19:12
@aadish yes I think that title will work well.

**Comment by aadish** [comment] 2016-08-24 19:14
awsm will go ahead and rename the GitHub repository to reflect the changes

**Comment by aadish** [comment] 2016-08-24 20:00
Github repo has been renamed and changes have been made inside babel, chipper, phetmarks, phet-info and all-sims to reflect the same

**Comment by aadish** [comment] 2016-09-20 22:34
sim has been renamed to gene expression essentials, closing

**Closed by aadish** 2016-09-20 22:34 UTC
