### ISSUE TITLE
Assertion failure from automated testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/gene-expression-essentials#5] opened 2015-07-08 21:21 UTC
```
Uncaught Error: Assertion failed: Rectangle requires 4 parameters
Error: Assertion failed: Rectangle requires 4 parameters
    at window.assertions.assertFunction (http://192.168.0.2:8080/assert/js/assert.js:22:13)
    at new Rectangle (http://192.168.0.2:8080/dot/js/Rectangle.js?bust=1436390261209:18:15)
    at new ManualGeneExpressionModel (http://192.168.0.2:8080/gene-expression-basics/js/manualgeneexpression/model/ManualGeneExpressionModel.js?bust=1436390261209:104:31)
    at ManualGeneExpressionScreen.Screen.call.backgroundColor [as createModel] (http://192.168.0.2:8080/gene-expression-basics/js/manualgeneexpression/ManualGeneExpressionScreen.js?bust=1436390261209:29:27)
    at ManualGeneExpressionScreen.inherit.initializeModel (http://192.168.0.2:8080/joist/js/Screen.js?bust=1436390261209:96:26)
    at ManualGeneExpressionScreen.inherit.initializeModelAndView (http://192.168.0.2:8080/joist/js/Screen.js?bust=1436390261209:113:12)
    at http://192.168.0.2:8080/joist/js/Sim.js?bust=1436390261209:394:14
    at Function.St (http://192.168.0.2:8080/sherpa/lib/lodash-2.4.1.min.js?bust=1436390261209:23:149)
    at new Sim (http://192.168.0.2:8080/joist/js/Sim.js?bust=1436390261209:392:7)
    at http://192.168.0.2:8080/gene-expression-basics/js/gene-expression-basics-main.js?bust=1436390261209:32:15
```

**Comment by aadish** [comment] 2016-09-20 22:33
cannot reproduce closing

**Closed by aadish** 2016-09-20 22:33 UTC
Labels: type:bug
