### ISSUE TITLE
Borders on florescent cells are grainy in iOS 13

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gene-expression-essentials#129] opened 2019-10-02 14:59 UTC
For https://github.com/phetsims/QA/issues/433, low priority.
The white outline of the cells on the last screen seem blurrier on iOS 13 than on iOS 12.  Easier to see when there are many cells, but can still be seen with just one.
![Image from iOS](https://user-images.githubusercontent.com/41024075/66055336-9daba080-e4f2-11e9-9674-cb49648bcd31.png)

**Comment by jonathanolson** [comment] 2019-10-02 17:31
I can't reproduce in the simulator, but I CAN reproduce on my iPhone.

**Comment by jbphet** [comment] 2019-10-23 22:08
I can reproduce using the as yet unnamed iOS 13 device, iOS version 13.1.3.  I can duplicate it **not** happening on Hopper, iOS version 12.4.1.

**Comment by jbphet** [comment] 2019-10-23 22:14
I think I've figured this out.  The cell shape is intentionally designed to be imperfect, i.e. to have some irregularities in order to appear more realistic.  On the iOS 13 device, which may have higher screen resolution, the joins between the different line segments are visible.  I add a `lineJoin` attribute to the Scenery node that represents the cell body and set the value to `round`, and the problem went away.

@KatieWoe - please have someone test the master version of this on various platforms and make sure that my change didn't have any unintentional consequences.  If it all looks good, please assign this back to me, and I'll move the change to the release branch and do a quick-and-easy maintenance release once the other big maintenance releases that are currently in progress have finished.

**Comment by KatieWoe** [comment] 2019-10-23 22:39
Things are looking ok after a quick check on master

**Comment by jbphet** [comment] 2019-10-28 19:10
I added the fix for this issue to the 1.0 release branch, built and tested on Chrome, Firefox, and iOS 13, and it all looks good.  Since this is a low-risk change, I'm planning to piggyback on the maintenance release that is currently in progress and have this change go out with that release.  That one is apparently close, so once it goes out, I'll verify this issue.

**Comment by jonathanolson** [comment] 2019-10-28 23:23
This should be out.

**Comment by jbphet** [comment] 2019-10-30 17:32
I just tested on the iOS 13 device, and the problem is fixed in the published version of the sim.  Closing.

**Closed by jbphet** 2019-10-30 17:32 UTC
Labels: type:bug
